spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        protocol: stateless
      #  stdio: false
      #  type: SYNC
      #  protocol: SSE
      #  annotation-scanner:
      #    enabled: true
      #  keep-alive-interval: 30s

server:
  port: 8081